import { useEffect, useState } from "react";
import * as api from "../api/client";
import StatusPill from "../components/StatusPill";

const TYPES = ["offer_letter", "listing_agreement", "buyer_rep_agreement", "closing_summary"];

export default function Documents() {
  const [documents, setDocuments] = useState([]);
  const [typeFilter, setTypeFilter] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [info, setInfo] = useState(null);

  async function load() {
    setLoading(true);
    try {
      const params = typeFilter ? { type: typeFilter } : {};
      const results = await api.listDocuments(params);
      setDocuments(results);
    } catch {
      setError("Couldn't load documents.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [typeFilter]);

  async function handleMarkSent(doc) {
    setError(null);
    setInfo(null);
    try {
      const result = await api.updateDocumentStatus(doc.id, "sent");
      if (result?.status === "pending") {
        setInfo("Sending this document requires approval and has been queued for review.");
      } else {
        setInfo("Marked as sent.");
      }
      await load();
    } catch (err) {
      setError(err.response?.data?.detail || "Couldn't update that document.");
    }
  }

  return (
    <>
      <div className="page-header">
        <div>
          <div className="eyebrow">Paperwork</div>
          <h1>Documents</h1>
        </div>
      </div>

      {error && <div className="error-banner">{error}</div>}
      {info && (
        <div
          className="error-banner"
          style={{ background: "var(--brass-soft)", color: "var(--brass)", borderColor: "var(--brass)" }}
        >
          {info}
        </div>
      )}

      <div className="filters">
        <select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}>
          <option value="">All types</option>
          {TYPES.map((t) => (
            <option key={t} value={t}>{t.replaceAll("_", " ")}</option>
          ))}
        </select>
      </div>

      {loading ? (
        <div className="empty-state">Loading…</div>
      ) : documents.length === 0 ? (
        <div className="empty-state">No documents yet — these appear automatically as deals progress.</div>
      ) : (
        <table>
          <thead>
            <tr>
              <th>Type</th>
              <th>Status</th>
              <th>Generated by</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {documents.map((doc) => (
              <tr key={doc.id}>
                <td style={{ textTransform: "capitalize" }}>{doc.type?.replaceAll("_", " ")}</td>
                <td><StatusPill status={doc.status} /></td>
                <td className="mono">{doc.generated_by}</td>
                <td style={{ display: "flex", gap: 8 }}>
                  <a
                    className="btn secondary small"
                    href={api.documentDownloadUrl(doc.id)}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Download
                  </a>
                  {doc.status === "draft" && (
                    <button className="btn small" onClick={() => handleMarkSent(doc)}>
                      Mark sent
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </>
  );
}
